### PR TITLE
Make better adjectives, make the only noun RobotSlayer because that's the only one that matters

### PR DESCRIPTION
**Pull request by BeepBot99**

### CODE REVIEW

**Comment by BeepBot99** [comment]
@Mesure73L Please merge this pull request

**Comment by Mesure73L** [comment]
not until you make the font hover thing on your design website

**Comment by BeepBot99** [comment]
ok fine you don't have to merge this then
cause i'm not making the font hover thing

**Comment by Mesure73L** [comment]
good

**Pull request closed without merging**
